<?php
/** @package Tasktracker::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("TaskMap.php");

/**
 * TaskDAO provides object-oriented access to the tasks table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Tasktracker::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class TaskDAO extends Phreezable
{
	/** @var string */
	public $Id;

	/** @var string */
	public $Project;

	/** @var string */
	public $Task;

	/** @var string */
	public $Hours;

	/** @var date */
	public $Startdate;

	/** @var date */
	public $Enddate;

	/** @var int */
	public $PkColumn;



}
?>